module.exports = {
  "concerts": [[
    [{
      "name": "Vancouver",
      "city": "Vancouver",
      "start_date": "20171005",
      "end_date": "20171015",
      "trip_id": 64,
      "eventResponse": {
        "last_item": null,
        "total_items": "55",
        "first_item": null,
        "page_number": "1",
        "page_size": "25",
        "page_items": null,
        "search_time": "0.056",
        "page_count": "3",
        "events": {
          "event": [{
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6A 1P2",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2813029",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/boris-18-event-/E0-001-104370002-6?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-104370002-6",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.0983812",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-08 20:00:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-07-03 07:31:47",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": {
                  "creator": "bobfather",
                  "linker": "evdb",
                  "name": "Boris",
                  "url": "http://concerts.eventful.com/Boris?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                  "id": "P0-001-000009680-2",
                  "short_bio": "Ambient / Metal / Experimental"
                }
              },
              "title": "Boris (18+ Event)",
              "venue_address": "254 East Hastings Street",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s3.evcdn.com/images/small/I0-001/001/215/746-1.jpeg_/boris-46.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s3.evcdn.com/images/medium/I0-001/001/215/746-1.jpeg_/boris-46.jpeg",
                  "height": "128"
                },
                "url": "http://s3.evcdn.com/images/small/I0-001/001/215/746-1.jpeg_/boris-46.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s3.evcdn.com/images/thumb/I0-001/001/215/746-1.jpeg_/boris-46.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-07-03 07:31:47",
              "venue_id": "V0-001-001623297-3",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Rickshaw Theatre",
              "venue_url": "http://vancouver.eventful.com/venues/rickshaw-theatre-/V0-001-001623297-3?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6Z 1L2",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.28",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/nick-murphy-charlotte-cardin-/E0-001-105145710-1?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-105145710-1",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.12",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-10 20:00:00",
              "tz_id": null,
              "description": "  ",
              "modified": "2017-07-28 22:55:46",
              "venue_display": "1",
              "tz_country": null,
              "performers": null,
              "title": "Nick Murphy with Charlotte Cardin",
              "venue_address": "918 Granville St",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": null,
              "created": "2017-07-28 22:55:46",
              "venue_id": "V0-001-000788398-8",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Vogue Theatre",
              "venue_url": "http://vancouver.eventful.com/venues/vogue-theatre-/V0-001-000788398-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6B 6G1",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2776612",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/weeknd-french-montana-/E0-001-103771114-6?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-103771114-6",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.1081074",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-05 19:30:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-06-13 16:35:57",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": [{
                    "creator": "ovoxo",
                    "linker": "evdb",
                    "name": "The Weeknd",
                    "url": "http://concerts.eventful.com/The-Weeknd?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000249303-6",
                    "short_bio": "ovoxo"
                  },
                  {
                    "creator": "frenchmontana",
                    "linker": "evdb",
                    "name": "French Montana",
                    "url": "http://concerts.eventful.com/French-Montana?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000066372-9",
                    "short_bio": "Rap / MMG"
                  }
                ]
              },
              "title": "The Weeknd & French Montana",
              "venue_address": "800 Griffiths Way",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s2.evcdn.com/images/small/I0-001/014/568/629-6.jpeg_/the-weeknd-29.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s2.evcdn.com/images/medium/I0-001/014/568/629-6.jpeg_/the-weeknd-29.jpeg",
                  "height": "128"
                },
                "url": "http://s2.evcdn.com/images/small/I0-001/014/568/629-6.jpeg_/the-weeknd-29.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s2.evcdn.com/images/thumb/I0-001/014/568/629-6.jpeg_/the-weeknd-29.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-06-13 12:33:54",
              "venue_id": "V0-001-000513842-2",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Rogers Arena",
              "venue_url": "http://vancouver.eventful.com/venues/rogers-arena-/V0-001-000513842-2?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": null,
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2764902",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/mickey-avalon-/E0-001-105552559-8?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-105552559-8",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.1000987",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-07 21:00:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-08-09 22:23:57",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": {
                  "creator": "interscoperecords",
                  "linker": "evdb",
                  "name": "Mickey Avalon",
                  "url": "http://concerts.eventful.com/Mickey-Avalon?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                  "id": "P0-001-000002789-3",
                  "short_bio": " Hip Hop / Rap / Punk"
                }
              },
              "title": "Mickey Avalon",
              "venue_address": "917 Main Street",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/small/I0-001/004/490/132-2.jpeg_/mickey-avalon-32.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s1.evcdn.com/images/medium/I0-001/004/490/132-2.jpeg_/mickey-avalon-32.jpeg",
                  "height": "128"
                },
                "url": "http://s1.evcdn.com/images/small/I0-001/004/490/132-2.jpeg_/mickey-avalon-32.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/thumb/I0-001/004/490/132-2.jpeg_/mickey-avalon-32.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-08-09 22:23:57",
              "venue_id": "V0-001-000299409-4",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "The Cobalt",
              "venue_url": "http://vancouver.eventful.com/venues/the-cobalt-/V0-001-000299409-4?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6B 4Y2",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2842860",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/lords-acid-/E0-001-103484303-7?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-103484303-7",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.1113390",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-08 20:00:00",
              "tz_id": null,
              "description": " with Combichrist, Christian Death, En Esch, Night Club<br> Lords of Acid, the legendary Belgian dance-industrial hybrid fronted by acid-house wizard Praga Khan, return with the act&#39;s first release in a decade coming this fall. In advance of the upcoming album, LOA presents the sleazy EP Little Mighty Rabbit. Chock full of LOAs patented brand of rocking electro-sex, the EP features three all new songs and remixes from KMFDM, tweaker, Christopher Lawrence, DJ Micro, AK1200, and more!",
              "modified": "2017-07-22 14:13:32",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": [{
                    "creator": "goldfrappe",
                    "linker": "evdb",
                    "name": "Lords Of Acid",
                    "url": "http://concerts.eventful.com/Lords-Of-Acid?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000024331-2",
                    "short_bio": "Industrial Sleaze"
                  },
                  {
                    "creator": "bobfather",
                    "linker": "evdb",
                    "name": "Combichrist",
                    "url": "http://concerts.eventful.com/Combichrist?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000008692-0",
                    "short_bio": "Metal / Experimental / Electro"
                  },
                  {
                    "creator": "christiandeath",
                    "linker": "evdb",
                    "name": "Christian Death",
                    "url": "http://concerts.eventful.com/Christian-Death?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000062166-2",
                    "short_bio": "Gothic Rock Metal Artist"
                  }
                ]
              },
              "title": "Lords Of Acid",
              "venue_address": "398 Richards Street",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/small/I0-001/000/310/848-1.jpg_/lords-of-acid-48.jpg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s1.evcdn.com/images/medium/I0-001/000/310/848-1.jpg_/lords-of-acid-48.jpg",
                  "height": "128"
                },
                "url": "http://s1.evcdn.com/images/small/I0-001/000/310/848-1.jpg_/lords-of-acid-48.jpg",
                "thumb": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/thumb/I0-001/000/310/848-1.jpg_/lords-of-acid-48.jpg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-06-02 14:19:17",
              "venue_id": "V0-001-000610607-7",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "The Red Room",
              "venue_url": "http://vancouver.eventful.com/venues/the-red-room-/V0-001-000610607-7?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6Z 1M1",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2759",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/la-witch-sugar-candy-mountain-/E0-001-105330582-0?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-105330582-0",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.128",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-07 20:00:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-08-13 06:04:59",
              "venue_display": "1",
              "tz_country": null,
              "performers": null,
              "title": "L.A. Witch, Sugar Candy Mountain",
              "venue_address": "2321 Main Street",
              "geocode_type": "Zip Code Based GeoCodes",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s3.evcdn.com/images/small/I0-001/037/006/626-7.jpeg_/la-witch-sugar-candy-mountain-26.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s3.evcdn.com/images/medium/I0-001/037/006/626-7.jpeg_/la-witch-sugar-candy-mountain-26.jpeg",
                  "height": "128"
                },
                "url": "http://s3.evcdn.com/images/small/I0-001/037/006/626-7.jpeg_/la-witch-sugar-candy-mountain-26.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s3.evcdn.com/images/thumb/I0-001/037/006/626-7.jpeg_/la-witch-sugar-candy-mountain-26.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-08-03 17:18:11",
              "venue_id": "V0-001-011201552-4",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "The Fox Cabaret",
              "venue_url": "http://vancouver.eventful.com/venues/the-fox-cabaret-/V0-001-011201552-4?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6B 6G1",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2776612",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/jimmy-buffett-/E0-001-102802656-9?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-102802656-9",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.1081074",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-13 20:00:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-05-08 14:56:31",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": {
                  "creator": "brian",
                  "linker": "evdb",
                  "name": "Jimmy Buffett",
                  "url": "http://concerts.eventful.com/Jimmy-Buffett?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                  "id": "P0-001-000000138-1",
                  "short_bio": "Gulf Western / Pop / Rock"
                }
              },
              "title": "Jimmy Buffett",
              "venue_address": "800 Griffiths Way",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s4.evcdn.com/images/small/I0-001/000/625/027-1.jpeg_/jimmy-buffett-27.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s4.evcdn.com/images/medium/I0-001/000/625/027-1.jpeg_/jimmy-buffett-27.jpeg",
                  "height": "128"
                },
                "url": "http://s4.evcdn.com/images/small/I0-001/000/625/027-1.jpeg_/jimmy-buffett-27.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s4.evcdn.com/images/thumb/I0-001/000/625/027-1.jpeg_/jimmy-buffett-27.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-05-08 14:56:31",
              "venue_id": "V0-001-000513842-2",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Rogers Arena",
              "venue_url": "http://vancouver.eventful.com/venues/rogers-arena-/V0-001-000513842-2?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6A 2S9",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2820824",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/north-mississippi-allstars-/E0-001-105045355-1?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-105045355-1",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.0996360",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-15 21:00:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-07-25 17:08:03",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": {
                  "creator": "redlightmanagement",
                  "linker": "evdb",
                  "name": "North Mississippi Allstars",
                  "url": "http://concerts.eventful.com/North-Mississippi-Allstars?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                  "id": "P0-001-000050754-8",
                  "short_bio": " Southern Rock / Blues"
                }
              },
              "title": "North Mississippi Allstars",
              "venue_address": "319 Main Street",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s2.evcdn.com/images/small/I0-001/000/759/321-6.jpeg_/north-mississippi-allstars-21.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s2.evcdn.com/images/medium/I0-001/000/759/321-6.jpeg_/north-mississippi-allstars-21.jpeg",
                  "height": "128"
                },
                "url": "http://s2.evcdn.com/images/small/I0-001/000/759/321-6.jpeg_/north-mississippi-allstars-21.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s2.evcdn.com/images/thumb/I0-001/000/759/321-6.jpeg_/north-mississippi-allstars-21.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-07-25 17:08:03",
              "venue_id": "V0-001-007059368-1",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Imperial Vancouver",
              "venue_url": "http://vancouver.eventful.com/venues/imperial-vancouver-/V0-001-007059368-1?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6A 2S9",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2820824",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/gryffin-autograf-dj-set-ayokay-/E0-001-105241957-9?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-105241957-9",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.0996360",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-08 21:00:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-08-01 02:25:56",
              "venue_display": "1",
              "tz_country": null,
              "performers": null,
              "title": "Gryffin, Autograf DJ Set, Ayokay",
              "venue_address": "319 Main Street",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/small/I0-001/037/009/916-8.jpeg_/gryffin-autograf-dj-set-ayokay-16.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s1.evcdn.com/images/medium/I0-001/037/009/916-8.jpeg_/gryffin-autograf-dj-set-ayokay-16.jpeg",
                  "height": "128"
                },
                "url": "http://s1.evcdn.com/images/small/I0-001/037/009/916-8.jpeg_/gryffin-autograf-dj-set-ayokay-16.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/thumb/I0-001/037/009/916-8.jpeg_/gryffin-autograf-dj-set-ayokay-16.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-07-31 17:55:37",
              "venue_id": "V0-001-007059368-1",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Imperial Vancouver",
              "venue_url": "http://vancouver.eventful.com/venues/imperial-vancouver-/V0-001-007059368-1?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V5K",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2858033",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/arcade-fire-phantogram-/E0-001-103469419-4?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-103469419-4",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.0429532",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-14 19:30:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-06-05 16:22:14",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": [{
                    "creator": "mechin",
                    "linker": "evdb",
                    "name": "Arcade Fire",
                    "url": "http://concerts.eventful.com/Arcade-Fire?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000062275-9",
                    "short_bio": "Indie/Alternative"
                  },
                  {
                    "creator": "artistdata",
                    "linker": "evdb",
                    "name": "Phantogram",
                    "url": "http://concerts.eventful.com/Phantogram?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000203331-1",
                    "short_bio": "Street Beat / Psych Pop / Electronic Rock"
                  }
                ]
              },
              "title": "Arcade Fire & Phantogram",
              "venue_address": "100 North Renfrew St.",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s3.evcdn.com/images/small/I0-001/014/946/182-6.jpeg_/arcade-fire-82.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s3.evcdn.com/images/medium/I0-001/014/946/182-6.jpeg_/arcade-fire-82.jpeg",
                  "height": "128"
                },
                "url": "http://s3.evcdn.com/images/small/I0-001/014/946/182-6.jpeg_/arcade-fire-82.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s3.evcdn.com/images/thumb/I0-001/014/946/182-6.jpeg_/arcade-fire-82.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-06-01 16:43:26",
              "venue_id": "V0-001-008563312-3",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Pacific Coliseum",
              "venue_url": "http://vancouver.eventful.com/venues/pacific-coliseum-/V0-001-008563312-3?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6B 5J3",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2801787",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/vancouver-new-music-201718-subscriptions-/E0-001-105742967-8?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-105742967-8",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.1196723",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-07 20:00:00",
              "tz_id": null,
              "description": " Purchase Concert Series Subscriptions for the 2017-18 Vancouver New Music lineup. Its a great way to see multiple shows and save money! There are two types of subscriptions available: Four-show Subscription $112 Grill/Jeck/Lemieux, Spectralism, Yoshihara/Sawai, Third Coast Percussion Six-show Subscription $168 Grill/Jeck/Lemieux, Spectralism, Yoshihara/Sawai, Third Coast Percussion, plus Uri Caine*, and ISCM2017 String Ensemble* *Only included with a 6 show subscription<br> <br> \n",
              "modified": "2017-08-16 03:28:39",
              "venue_display": "1",
              "tz_country": null,
              "performers": null,
              "title": "Vancouver New Music 2017-18 Subscriptions",
              "venue_address": "823 Seymour Street, 2nd Floor",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": null,
              "created": "2017-08-16 03:28:39",
              "venue_id": "V0-001-005072676-8",
              "tz_city": null,
              "stop_time": "2017-10-07 22:00:00",
              "venue_name": "Orpheum Annex Theatre",
              "venue_url": "http://vancouver.eventful.com/venues/orpheum-annex-theatre-/V0-001-005072676-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": null,
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2505",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/chris-lake-lose-my-mind-tour-vancouver-/E0-001-104322640-9?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-104322640-9",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.112",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-07 22:00:00",
              "tz_id": null,
              "description": " <strong>Presented by Blueprint Events & MIA </strong><br><strong>Saturday October 7 2017 at M.I.A.</strong><br><p>Doors 10pm - 3am<p><a href=\"https://www.facebook.com/events/106493603258669/\" rel=\"nofollow\"><i></i>  facebook page</a><a href=\"http://bit.ly/2u91jQF\" rel=\"nofollow\">tickets</a><p><p>One of electronic music’s most prominent figures and <a href=\"https://www.facebook.com/risingmusic/\" rel=\"nofollow\">Rising Music</a> label founder <a href=\"https://www.facebook.com/chrislake/\" rel=\"nofollow\">Chris Lake</a> brings his Lose My Mind Tour to MIA on Saturday, Oct. 7th alongside special guest <a href=\"https://www.facebook.com/noisefrenzy/\" rel=\"nofollow\">Noise Frenzy</a>!<p>Spotify Pre-sale: Tomorrow, June 27th 10am to Wed, June 28th 10pm<br> Password: losemymind<p>General Onsale: Thursday June 29th via <a href=\"http://bit.ly/2u91jQF\" rel=\"nofollow\">bit.ly/2u91jQF</a><p>19+ with government ID required<br> Reserve table service packages at info@areyoumia.com<br> Support TBA<p>Stay connected with us at M.I.A.: Engage and share with us on social (both before and during the event) by keeping tabs on the <a href=\"https://www.facebook.com/hashtag/areyoumia\" rel=\"nofollow\">#AreYouMIA</a> hashtag!</p></p></p></p></p></p></p></p>",
              "modified": "2017-07-02 17:03:29",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": {
                  "creator": "SwitchProductions",
                  "linker": "evdb",
                  "name": "Chris Lake",
                  "url": "http://concerts.eventful.com/Chris-Lake?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                  "id": "P0-001-000013290-0",
                  "short_bio": "House"
                }
              },
              "title": "Chris Lake: Lose My Mind Tour – Vancouver",
              "venue_address": "350 Water Street, Vancouver,BC, V6B 1B6",
              "geocode_type": "City Based GeoCodes",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/small/I0-001/004/186/700-9.jpeg_/chris-lake-00.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s1.evcdn.com/images/medium/I0-001/004/186/700-9.jpeg_/chris-lake-00.jpeg",
                  "height": "128"
                },
                "url": "http://s1.evcdn.com/images/small/I0-001/004/186/700-9.jpeg_/chris-lake-00.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/thumb/I0-001/004/186/700-9.jpeg_/chris-lake-00.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-07-01 19:15:00",
              "venue_id": "V0-001-008784989-8",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "M.I.A.",
              "venue_url": "http://vancouver.eventful.com/venues/mia-/V0-001-008784989-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6E 1M3",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.280383",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/gorgon-city-/E0-001-104322650-6?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-104322650-6",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.131214",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-06 22:00:00",
              "tz_id": null,
              "description": " <strong>Presented by Blueprint </strong><br><strong>Friday October 6 2017 at Celebrities</strong><br><p>Doors 10pm - <a href=\"http://blueprint.electrostub.com/event.cfm?id=184773&cart\" rel=\"nofollow\">tickets</a><p><p>Exploring innovative approaches to deep, crossover club music, <a href=\"https://www.facebook.com/gorgoncity/\" rel=\"nofollow\">Gorgon City</a> presents ‘Kingdom’ on Friday, October 6th at <a href=\"https://www.facebook.com/hashtag/stereotypefridays\" rel=\"nofollow\">#StereotypeFridays</a>!<p>Tickets on sale Weds, June 28th at 10am: <a href=\"http://bit.ly/2tdovAB\" rel=\"nofollow\">bit.ly/2tdovAB</a><p>Presented by Blueprint Events & Celebrities Nightclub<br> w/ DJ’s TBA – 19+ Only<p>Stay connected with this special edition of Stereotype: Engage and share with us on social (both before and during the event) by keeping tabs on the & #StereotypeFridays hashtag!</p></p></p></p></p></p>",
              "modified": "2017-07-02 17:03:29",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": {
                  "creator": "jboasee0c71",
                  "linker": "evdb",
                  "name": "Gorgon City",
                  "url": "http://concerts.eventful.com/performers/gorgon-city-/P0-001-014196459-4?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                  "id": "P0-001-014196459-4",
                  "short_bio": "EDM"
                }
              },
              "title": "Gorgon City",
              "venue_address": "Davie St",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": null,
              "created": "2017-07-01 19:15:15",
              "venue_id": "V0-001-000609741-4",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Celebrities",
              "venue_url": "http://vancouver.eventful.com/venues/celebrities-/V0-001-000609741-4?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": null,
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2505",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/vancouver-chamber-choir-masters-/E0-001-105848413-1?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-105848413-1",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.112",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-13 20:00:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-08-18 08:33:13",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": {
                  "creator": "BCcat",
                  "linker": "evdb",
                  "name": "Vancouver Chamber Choir",
                  "url": "http://concerts.eventful.com/Vancouver-Chamber-Choir?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                  "id": "P0-001-000218019-6",
                  "short_bio": "The Vancouver Chamber Choir is Canada's outstanding professional vocal ensemble. Based on the Pacific Coast in British Columbia, conductor Jon Washburn and his twenty singers are noted for their diverse repertoire and performing excellence. The ACDA Choral Journal has declared the VCC to be \"as fine a vocal chamber group as any in the world today.\""
                }
              },
              "title": "Vancouver Chamber Choir: The Masters",
              "venue_address": "2205 W. 45th Ave",
              "geocode_type": "City Based GeoCodes",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/small/I0-001/002/607/212-1.jpeg_/vancouver-chamber-choir-12.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s1.evcdn.com/images/medium/I0-001/002/607/212-1.jpeg_/vancouver-chamber-choir-12.jpeg",
                  "height": "128"
                },
                "url": "http://s1.evcdn.com/images/small/I0-001/002/607/212-1.jpeg_/vancouver-chamber-choir-12.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/thumb/I0-001/002/607/212-1.jpeg_/vancouver-chamber-choir-12.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-08-18 08:33:13",
              "venue_id": "V0-001-008349578-7",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Ryerson United Church",
              "venue_url": "http://vancouver.eventful.com/venues/ryerson-united-church-/V0-001-008349578-7?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6B 6G1",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2776612",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/kings-leon-dawes-/E0-001-102379855-5?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-102379855-5",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.1081074",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-11 19:30:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-04-26 08:14:57",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": [{
                    "creator": "VMGMT",
                    "linker": "evdb",
                    "name": "Kings of Leon",
                    "url": "http://concerts.eventful.com/Kings-of-Leon?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000017370-3",
                    "short_bio": "Southern Rock / Folk / Alternative"
                  },
                  {
                    "creator": "wahooalex02",
                    "linker": "evdb",
                    "name": "Dawes",
                    "url": "http://concerts.eventful.com/performers/dawes-/P0-001-000246564-4?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000246564-4",
                    "short_bio": "Folk Rock"
                  }
                ]
              },
              "title": "Kings of Leon & Dawes",
              "venue_address": "800 Griffiths Way",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s3.evcdn.com/images/small/I0-001/016/989/422-6.jpeg_/kings-of-leon-22.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s3.evcdn.com/images/medium/I0-001/016/989/422-6.jpeg_/kings-of-leon-22.jpeg",
                  "height": "128"
                },
                "url": "http://s3.evcdn.com/images/small/I0-001/016/989/422-6.jpeg_/kings-of-leon-22.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s3.evcdn.com/images/thumb/I0-001/016/989/422-6.jpeg_/kings-of-leon-22.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-04-24 12:57:09",
              "venue_id": "V0-001-000513842-2",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Rogers Arena",
              "venue_url": "http://vancouver.eventful.com/venues/rogers-arena-/V0-001-000513842-2?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6B 6G1",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2776612",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/imagine-dragons-evolve-tour-/E0-001-103130006-3?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-103130006-3",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.1081074",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-08 19:30:00",
              "tz_id": null,
              "description": "<strong>Sunday October 8, 2017 7:30pm</strong><p><strong>Rogers Arena, Vancouver</strong><p>Imagine Dragons are ready to Evolve, according to their new album title, set for release on June 23, 2017. The new album includes songs &quot;Whatever It Takes&quot;, &quot;Believer&quot; and &quot;Thunder&quot;, all on the Billboard Hot 100 list.<p>Imagine Dragons will be joined by Grouplove and K. Flay on their North American leg of the Evolve World Tour.<p><em>For tickets and more information please visit <a href=\"http://ticketmaster.evyy.net/c/380594/264167/4272?u=https%3A%2F%2Fwww.ticketmaster.ca%2Fimagine-dragons-evolve-tour-vancouver-british-columbia-10-08-2017%2Fevent%2F110052A8804F5E6E%3Fartistid%3D1435919%26majorcatid%3D10001%26minorcatid%3D1\" rel=\"nofollow\">ticketmaster.ca</a></em>\n</p></p></p></p>",
              "modified": "2017-06-28 16:26:57",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": {
                  "creator": "evdb",
                  "linker": "sara_sd",
                  "name": "Imagine Dragons",
                  "url": "http://concerts.eventful.com/Imagine-Dragons?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                  "id": "P0-001-000253168-2",
                  "short_bio": "Alternative / Pop / Rock"
                }
              },
              "title": "Imagine Dragons: Evolve Tour",
              "venue_address": "800 Griffiths Way",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "sara_sd",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/small/I0-001/015/001/088-6.jpeg_/imagine-dragons-88.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s1.evcdn.com/images/medium/I0-001/015/001/088-6.jpeg_/imagine-dragons-88.jpeg",
                  "height": "128"
                },
                "url": "http://s1.evcdn.com/images/small/I0-001/015/001/088-6.jpeg_/imagine-dragons-88.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/thumb/I0-001/015/001/088-6.jpeg_/imagine-dragons-88.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-05-20 07:43:54",
              "venue_id": "V0-001-000513842-2",
              "tz_city": null,
              "stop_time": "2017-10-08 00:00:00",
              "venue_name": "Rogers Arena",
              "venue_url": "http://vancouver.eventful.com/venues/rogers-arena-/V0-001-000513842-2?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V5K",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2858033",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/lauryn-hill-nas-/E0-001-103413149-1?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-103413149-1",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.0429532",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-11 18:30:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-05-30 12:37:37",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": [{
                    "creator": "ZIMROCKS",
                    "linker": "evdb",
                    "name": "Lauryn Hill",
                    "url": "http://concerts.eventful.com/Lauryn-Hill?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000165214-6",
                    "short_bio": "Hip Hop/ R&B"
                  },
                  {
                    "creator": "Naheed7f79d",
                    "linker": "evdb",
                    "name": "NAS",
                    "url": "http://concerts.eventful.com/NAS?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000011218-2",
                    "short_bio": "Rap / Brooklyn MC / Hip-Hop"
                  }
                ]
              },
              "title": "Lauryn Hill & Nas",
              "venue_address": "100 North Renfrew St.",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/small/I0-001/003/815/440-0.jpeg_/lauryn-hill-40.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s1.evcdn.com/images/medium/I0-001/003/815/440-0.jpeg_/lauryn-hill-40.jpeg",
                  "height": "128"
                },
                "url": "http://s1.evcdn.com/images/small/I0-001/003/815/440-0.jpeg_/lauryn-hill-40.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s1.evcdn.com/images/thumb/I0-001/003/815/440-0.jpeg_/lauryn-hill-40.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-05-30 12:37:37",
              "venue_id": "V0-001-008563312-3",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Pacific Coliseum",
              "venue_url": "http://vancouver.eventful.com/venues/pacific-coliseum-/V0-001-008563312-3?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": null,
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2648785",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/altj-/E0-001-102050882-7?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-102050882-7",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.2524963",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-13 20:00:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-06-25 00:20:21",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": {
                  "creator": "evdb",
                  "linker": "evdb",
                  "name": "alt-J",
                  "url": "http://concerts.eventful.com/Alt-J?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                  "id": "P0-001-005622848-0",
                  "short_bio": "Music"
                }
              },
              "title": "Alt-J",
              "venue_address": "University Of British Columbia",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s2.evcdn.com/images/small/I0-001/012/700/985-5.jpeg_/altj-85.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s2.evcdn.com/images/medium/I0-001/012/700/985-5.jpeg_/altj-85.jpeg",
                  "height": "128"
                },
                "url": "http://s2.evcdn.com/images/small/I0-001/012/700/985-5.jpeg_/altj-85.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s2.evcdn.com/images/thumb/I0-001/012/700/985-5.jpeg_/altj-85.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-04-12 14:33:04",
              "venue_id": "V0-001-001077794-2",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Thunderbird Stadium",
              "venue_url": "http://vancouver.eventful.com/venues/thunderbird-stadium-/V0-001-001077794-2?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6Z 1L2",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.28",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/nick-murphy-/E0-001-102842553-9?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-102842553-9",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.12",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-09 20:00:00",
              "tz_id": null,
              "description": " with Charlotte Cardin, Heathered Pearls<br> One half of UK production duo Bassheads, along with Desa Murphy.",
              "modified": "2017-07-22 14:09:21",
              "venue_display": "1",
              "tz_country": null,
              "performers": null,
              "title": "Nick Murphy",
              "venue_address": "918 Granville St",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": null,
              "created": "2017-05-10 00:04:01",
              "venue_id": "V0-001-000788398-8",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Vogue Theatre",
              "venue_url": "http://vancouver.eventful.com/venues/vogue-theatre-/V0-001-000788398-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6A 1P2",
              "going_count": null,
              "all_day": "2",
              "latitude": "49.2813029",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/cancelled-poptone-guest-art-decco-/E0-001-051410782-7?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-051410782-7",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.0983812",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-13 00:00:00",
              "tz_id": null,
              "description": " October 13th<br>Timbre Concerts presents<br>CANCELLED: Poptone with guest Art D&#39;Ecco",
              "modified": "2017-07-22 14:37:46",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": [{
                    "creator": "metalvinny",
                    "linker": "evdb",
                    "name": "The Black Dahlia Murder",
                    "url": "http://concerts.eventful.com/The-Black-Dahlia-Murder?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000004485-4",
                    "short_bio": "Death metal"
                  },
                  {
                    "creator": "vicdaen",
                    "linker": "evdb",
                    "name": "orange goblin",
                    "url": "http://concerts.eventful.com/orange-goblin?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000032345-0",
                    "short_bio": "Heavy metal/doom act from the UK"
                  },
                  {
                    "creator": "overthecoals",
                    "linker": "evdb",
                    "name": "Over the Coals",
                    "url": "http://concerts.eventful.com/Over-the-Coals?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000020391-6",
                    "short_bio": "Real Canadian Metal from Vancouver, B.C."
                  },
                  {
                    "creator": "standdownmilitia",
                    "linker": "evdb",
                    "name": "Stand Down",
                    "url": "http://concerts.eventful.com/Stand-Down?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000038603-3",
                    "short_bio": "hard rock"
                  },
                  {
                    "creator": "ninnghizzhidda",
                    "linker": "evdb",
                    "name": "Maruta",
                    "url": "http://concerts.eventful.com/Maruta?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000058703-0",
                    "short_bio": "Grindcore (Willowtip Records)"
                  },
                  {
                    "creator": "evdb",
                    "linker": "evdb",
                    "name": "Carnage The Executioner",
                    "url": "http://concerts.eventful.com/Carnage-The-Executioner?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000257206-9",
                    "short_bio": "Hip Hop/Rap / Vocal"
                  },
                  {
                    "creator": "indietickets",
                    "linker": "evdb",
                    "name": "DJ Abilities",
                    "url": "http://concerts.eventful.com/DJ-Abilities?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000012045-5",
                    "short_bio": "Hip Hop / Turntablism / Rock"
                  }
                ]
              },
              "title": "CANCELLED: Poptone with guest Art D'Ecco",
              "venue_address": "254 East Hastings Street",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s4.evcdn.com/images/small/I0-001/000/408/359-6.jpg_/the-black-dahlia-murder-59.jpg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s4.evcdn.com/images/medium/I0-001/000/408/359-6.jpg_/the-black-dahlia-murder-59.jpg",
                  "height": "128"
                },
                "url": "http://s4.evcdn.com/images/small/I0-001/000/408/359-6.jpg_/the-black-dahlia-murder-59.jpg",
                "thumb": {
                  "width": "48",
                  "url": "http://s4.evcdn.com/images/thumb/I0-001/000/408/359-6.jpg_/the-black-dahlia-murder-59.jpg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2012-09-23 13:15:26",
              "venue_id": "V0-001-001623297-3",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Rickshaw Theatre",
              "venue_url": "http://vancouver.eventful.com/venues/rickshaw-theatre-/V0-001-001623297-3?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": null,
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2505",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/diplo-/E0-001-105823566-9?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-105823566-9",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.112",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-07 19:00:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-08-17 23:59:40",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": {
                  "creator": "Photoman",
                  "linker": "evdb",
                  "name": "Diplo",
                  "url": "http://concerts.eventful.com/Diplo?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                  "id": "P0-001-000010989-6",
                  "short_bio": "DJ supreme!"
                }
              },
              "title": "Diplo",
              "venue_address": "100 N. Renfrew St.",
              "geocode_type": "City Based GeoCodes",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s2.evcdn.com/images/small/I0-001/021/950/721-6.jpeg_/diplo-21.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s2.evcdn.com/images/medium/I0-001/021/950/721-6.jpeg_/diplo-21.jpeg",
                  "height": "128"
                },
                "url": "http://s2.evcdn.com/images/small/I0-001/021/950/721-6.jpeg_/diplo-21.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s2.evcdn.com/images/thumb/I0-001/021/950/721-6.jpeg_/diplo-21.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-08-17 23:59:40",
              "venue_id": "V0-001-004150431-3",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Pacific National Exhibition - Rogers Amphitheatre",
              "venue_url": "http://vancouver.eventful.com/venues/pacific-national-exhibition-rogers-amphithe-/V0-001-004150431-3?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6A 2V8",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2764902",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/cribs-tickets-19-event-/E0-001-105240595-6?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-105240595-6",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.1000987",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-10 20:00:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-07-31 16:00:26",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": {
                  "creator": "wbrecords",
                  "linker": "evdb",
                  "name": "The Cribs",
                  "url": "http://concerts.eventful.com/The-Cribs?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                  "id": "P0-001-000020310-1",
                  "short_bio": " Punk / Indie"
                }
              },
              "title": "The Cribs Tickets (19+ Event)",
              "venue_address": "917 Main street",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s3.evcdn.com/images/small/I0-001/002/993/146-3.jpeg_/the-cribs-46.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s3.evcdn.com/images/medium/I0-001/002/993/146-3.jpeg_/the-cribs-46.jpeg",
                  "height": "128"
                },
                "url": "http://s3.evcdn.com/images/small/I0-001/002/993/146-3.jpeg_/the-cribs-46.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s3.evcdn.com/images/thumb/I0-001/002/993/146-3.jpeg_/the-cribs-46.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2017-07-31 16:00:26",
              "venue_id": "V0-001-007186760-8",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "The Cobalt",
              "venue_url": "http://vancouver.eventful.com/venues/the-cobalt-/V0-001-007186760-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6A 1P2",
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2813029",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/menzingers-guests-/E0-001-049476969-5?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-049476969-5",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.0983812",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-06 19:00:00",
              "tz_id": null,
              "description": " October 6th<br>MRG Concerts presents<br>The Menzingers with guests",
              "modified": "2017-07-15 18:52:38",
              "venue_display": "1",
              "tz_country": null,
              "performers": {
                "performer": [{
                    "creator": "bauny91",
                    "linker": "evdb",
                    "name": "The Menzingers",
                    "url": "http://concerts.eventful.com/The-Menzingers?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000198792-7",
                    "short_bio": null
                  },
                  {
                    "creator": "gwald43",
                    "linker": "evdb",
                    "name": "Thee Oh Sees",
                    "url": "http://concerts.eventful.com/Thee-Oh-Sees?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000195451-2",
                    "short_bio": "Hyphy / Emotronic / Psychedelic"
                  },
                  {
                    "creator": "chigaze",
                    "linker": "evdb",
                    "name": "Vieux Farka Touré",
                    "url": "http://concerts.eventful.com/Vieux-Farka-Tour?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000073140-0",
                    "short_bio": "Mali Blues Guitar"
                  },
                  {
                    "creator": "Necrotide",
                    "linker": "evdb",
                    "name": "Sic Alps",
                    "url": "http://concerts.eventful.com/Sic-Alps?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                    "id": "P0-001-000158758-7",
                    "short_bio": "Indie Rock"
                  }
                ]
              },
              "title": "The Menzingers with guests",
              "venue_address": "254 East Hastings Street",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": {
                "small": {
                  "width": "48",
                  "url": "http://s2.evcdn.com/images/small/I0-001/039/003/321-2.jpeg_/menzingers-guests-21.jpeg",
                  "height": "48"
                },
                "width": "48",
                "caption": null,
                "medium": {
                  "width": "128",
                  "url": "http://s2.evcdn.com/images/medium/I0-001/039/003/321-2.jpeg_/menzingers-guests-21.jpeg",
                  "height": "128"
                },
                "url": "http://s2.evcdn.com/images/small/I0-001/039/003/321-2.jpeg_/menzingers-guests-21.jpeg",
                "thumb": {
                  "width": "48",
                  "url": "http://s2.evcdn.com/images/thumb/I0-001/039/003/321-2.jpeg_/menzingers-guests-21.jpeg",
                  "height": "48"
                },
                "height": "48"
              },
              "created": "2012-07-08 08:55:41",
              "venue_id": "V0-001-001623297-3",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Rickshaw Theatre",
              "venue_url": "http://vancouver.eventful.com/venues/rickshaw-theatre-/V0-001-001623297-3?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": "V6A 1T6",
              "going_count": null,
              "all_day": "2",
              "latitude": "49.2805198",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/max-all-ages-/E0-001-104074212-8?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-104074212-8",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-123.1007312",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-05 00:00:00",
              "tz_id": null,
              "description": null,
              "modified": "2017-07-01 19:06:49",
              "venue_display": "1",
              "tz_country": null,
              "performers": null,
              "title": "MAX (All Ages)",
              "venue_address": "147 E Pender",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": null,
              "created": "2017-06-24 14:45:20",
              "venue_id": "V0-001-002521059-3",
              "tz_city": null,
              "stop_time": null,
              "venue_name": "Fortune Sound Club",
              "venue_url": "http://vancouver.eventful.com/venues/fortune-sound-club-/V0-001-002521059-3?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
              "watching_count": null,
              "olson_path": "America/Vancouver",
              "calendar_count": null,
              "comment_count": null,
              "region_abbr": "BC",
              "postal_code": null,
              "going_count": null,
              "all_day": "0",
              "latitude": "49.2388209",
              "groups": null,
              "url": "http://vancouver.eventful.com/events/episodes-life-robert-schumann-/E0-001-104219927-8?utm_source=apis&utm_medium=apim&utm_campaign=apic",
              "id": "E0-001-104219927-8",
              "privacy": "1",
              "city_name": "Vancouver",
              "link_count": null,
              "longitude": "-122.8611354",
              "country_name": "Canada",
              "country_abbr": "CAN",
              "region_name": "British Columbia",
              "start_time": "2017-10-14 19:30:00",
              "tz_id": null,
              "description": " Learn about the life of Robert Schumann through his music. Pianist Barry Tan, with guests Ben Goheen, Peter Ing and Will Chen, will perform three Schumann works from different periods in the composer&#39;s life, while recounting fascinating episodes that are representative of each phase. Hear about Schumann&#39;s love life with his wife, the great pianist Clara Schumann, and learn about his struggles coping with depression and mental illness while enjoying Fantasiestucke (Fantasy Pieces), Op.12 (Early Period), Piano Quartet in Eb Major, Op.47 (Middle Period) and Waldszenen (Forest Scenes), Op.82 (Late Period).<br> <br> \n",
              "modified": "2017-06-29 03:04:13",
              "venue_display": "1",
              "tz_country": null,
              "performers": null,
              "title": "Episodes from the Life of Robert Schumann",
              "venue_address": "1120 Brunette Avenue",
              "geocode_type": "EVDB Geocoder",
              "tz_olson_path": null,
              "recur_string": null,
              "calendars": null,
              "owner": "evdb",
              "going": null,
              "country_abbr2": "CA",
              "image": null,
              "created": "2017-06-29 03:04:13",
              "venue_id": "V0-001-000722086-0",
              "tz_city": null,
              "stop_time": "2017-10-14 21:30:00",
              "venue_name": "Place des Arts",
              "venue_url": "http://vancouver.eventful.com/venues/place-des-arts-/V0-001-000722086-0?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            }
          ]
        }
      }
    }]
  ]]
}